#!/bin/bash
---

- hosts: localhost
  vars_files:
    - vars.yml

#- name: Include varid.yml
#  include_vars:
#    file: varid.yml
#    name: instanceid
  tasks:
    - ec2:
       state: 'absent'
       region: us-west-2
       instance_id: '{{ instance_id }}'
       instance_tags:
         Name: ansibleec2
